//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFabEAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master
    {
        public int Id { get; set; }
        public string CodeBar { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public int Line { get; set; }
        public int Category { get; set; }
        public int Presentation { get; set; }
        public int UntMeasure { get; set; }
        public decimal Minimum { get; set; }
        public decimal Maximum { get; set; }
        public decimal Cost { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string State { get; set; }
    }
}
