//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFabEAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movements
    {
        public string Branch { get; set; }
        public int Warehouse { get; set; }
        public int Master { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public string Journal { get; set; }
        public string Reference { get; set; }
        public string MovType { get; set; }
        public string TrnType { get; set; }
        public decimal Quantity { get; set; }
        public decimal Cost { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string State { get; set; }
        public int TrnNumber { get; set; }
    }
}
