//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFabEAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Order { get; set; }
        public string Branch { get; set; }
        public int Line { get; set; }
        public string Warehouse { get; set; }
        public int Product { get; set; }
        public string UntMeasure { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public string PriceCode { get; set; }
        public decimal Discount { get; set; }
        public string DiscountCode { get; set; }
        public decimal Cost { get; set; }
        public string State { get; set; }
    }
}
