//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFabEAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacology
    {
        public int Master { get; set; }
        public Nullable<int> Lab { get; set; }
        public string Composition { get; set; }
        public string ActionPharmacology { get; set; }
        public string Dose { get; set; }
        public string Treatment { get; set; }
        public Nullable<bool> Prescription { get; set; }
    }
}
