//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFabEAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTakeInventoryDetail
    {
        public int StockTakeNro { get; set; }
        public int Warehouse { get; set; }
        public int Master { get; set; }
        public decimal Stock { get; set; }
        public decimal StockOnHand { get; set; }
        public decimal SrockDifference { get; set; }
        public string Location { get; set; }
        public System.DateTime RegisterDate { get; set; }
    }
}
