//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFabEAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferReturn
    {
        public int Transfer { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int Line { get; set; }
        public int SrcWarehouse { get; set; }
        public int TrgWarehouse { get; set; }
        public int Master { get; set; }
        public int UntMeasure { get; set; }
        public decimal Quantity { get; set; }
        public string User { get; set; }
        public System.DateTime RegisterDate { get; set; }
    }
}
