//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFabEAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public string Branch { get; set; }
        public int Warehouse1 { get; set; }
        public int Master { get; set; }
        public decimal QtyOnHand { get; set; }
        public decimal Quantity { get; set; }
        public decimal LastCost { get; set; }
    }
}
